url: http://tillahoffmann.github.io
exclude:
  - .git
  - venv
remote_theme: jekyll/minima@49f6dce0727a2441f0b0c265b41b5efc7b042eb6
title: Till Hoffmann
show_excerpts: true
header_pages:
  - index.html
  - research.md
  - teaching.md
  - about.md
repository: tillahoffmann/tillahoffmann.github.io
paginate: 5
plugins:
  - jekyll-paginate
  - jekyll-remote-theme

minima:
  social_links:
    twitter: tillahoffmann
    github: tillahoffmann
    linkedin: tillahoffmann
    scholar: 0VvYpCsAAAAJ
  skin: harvard
