name: Till's Website
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.10"
          cache: pip
      - name: Install python dependencies
        run: pip install --no-dependencies -r requirements.txt
      - name: Verify asset directories
        run: python .github/workflows/verify-asset-directories.py
      - name: Compile the notebooks
        run: make notebook-posts
